### ISSUE TITLE
P vs NP

### ISSUE THREAD

**Issue by lucasmoschen** [arademaker/md-2019.2#1]
Professor, não sei quão importante é isso, mas na aula do dia 27/08, tu falastes sobre problemas do conjunto P, e problemas do conjunto NP, sendo os primeiros com computação em tempo polinomial e os segundos com checagem em tempo polinomial. Também tu esclareceu dúvidas sobre Máquina de Turing.

**Comment by arademaker** [comment]
Obrigado @lucasmoschen ! Em 11d95d9 acrescentei comentários.
